### ISSUE TITLE
VST3 plugin saved incorrectly on an aarch64 Linux architecture

### ISSUE THREAD

**Issue by dguillemyn** [utokusa/OS-251#15]
I have compiled this awesome synth on an aarch64 Linux successfully. Only problem encountered was that it stored the VST3  plugin under ~./vst3/OS-251.vst3/Contents/**arm64**-linux/ . Instead it should be ~./vst3/OS-251.vst3/Contents/**aarch64**-linux/

**Comment by utokusa** [comment]
Thanks for reporting. I guess it's because of this JUCE's issue https://github.com/juce-framework/JUCE/issues/819 .
Currently OS-251 uses JUCE 6.0.5 while the bug was fixed in 6.0.8. So I created branch `feature/upgrade_juce_to_6_1_0` which uses 6.1.0.

Could you try it?

**Comment by dguillemyn** [comment]
works!

One further note:   compiling with -ffast-math is disallowed by react_juce:
`51%] Building CXX object src/CMakeFiles/Os251.dir/__/lib/react-juce/react_juce/react_juce.cpp.o
In file included from /media/shcd/dev/OS-251/lib/react-juce/react_juce/./duktape/src-noline/duktape.h:195,
                 from /media/shcd/dev/OS-251/lib/react-juce/react_juce/./duktape/src-noline/duktape.c:188,
                 from /media/shcd/dev/OS-251/lib/react-juce/react_juce/core/EcmascriptEngine.cpp:67,
                 from /media/shcd/dev/OS-251/lib/react-juce/react_juce/react_juce.cpp:78:
/media/shcd/dev/OS-251/lib/react-juce/react_juce/./duktape/src-noline/duk_config.h:2861:2: error: #error __FAST_MATH__ defined, refusing to compile
`
which is a bit a pity as it  typically speed up the DSP considerably...

**Comment by utokusa** [comment]
Thanks for confirming and the information.

For fast math, I created an issue.
https://github.com/utokusa/OS-251/issues/20#issue-989065451

I will try to find a way to address that.
