### ISSUE TITLE
LV2 version?

### ISSUE THREAD

**Issue by dromer** [utokusa/OS-251#18]
The age old question to JUCE projects: will you add LV2 support by using one of https://github.com/lv2-porting-project/JUCE or https://github.com/DISTRHO/juce ?

Jatin wrote a nice blogpost about the process (it's fairly simple): https://jatinchowdhury18.medium.com/building-lv2-plugins-with-juce-and-cmake-d1f8937dbac3

cheers

**Comment by utokusa** [comment]
Thanks for the interesting information :)
I will try it.

**Comment by dguillemyn** [comment]
Note that e.g. Odin2 makes use of the lv2-porting-project to support LV2 plugins, see https://github.com/TheWaveWarden/odin2  (didn't try it out though)

**Comment by Baggypants** [comment]
Would really help for using OS-251 on arm like the Raspberry Pi.

**Comment by utokusa** [comment]
Hi, everyone.
I tried https://github.com/lv2-porting-project/JUCE and it works well!

I merged the PR (#27) to master, but it's not released yet.
But you can try the binary from here (login required).
https://github.com/utokusa/OS-251/actions/runs/1265684772#:~:text=Size-,OS-251-Linux,-8.22%20MB

Thank you for all information and comments :)

**Comment by dromer** [comment]
Cool! Will try building it :)

JUCE devs are working on getting official LV2 support in, but this will be some time away before it can be used.
Until then: great work!

**Comment by dromer** [comment]
Can confirm the build works!

I am a bit concerned that a plain `make` also installs the build artifacts. It would be preferred if this is a separate install step

**Comment by utokusa** [comment]
@dromer Thanks for trying!

About other platforms, I included LV2 binary in CD only for Linux because I guess most of LV2 users (who want binary) use Linux.
But if more people ask for LV2 binary for other platforms, I will consider it!

About the installation, I think it's because of `COPY_PLUGIN_AFTER_BUILD TRUE` in src/CMakeLists.txt.
So for now, please comment out the line if you don't want that behavior.

**Comment by dromer** [comment]
> About other platforms, I included LV2 binary in CD only for Linux because I guess most of LV2 users (who want binary) use Linux.

Build it and they will come ;)

We have many hosts now: reaper, ardour, carla, zrythm, mixxx, etc.

**Comment by utokusa** [comment]
That's a good point 😁
I will start from trying LV2 version on mac and windows.

**Comment by utokusa** [comment]
According to https://github.com/lv2-porting-project/JUCE/issues/9,  it seems like https://github.com/lv2-porting-project/JUCE doesn't support mac and windows.
And I don't have enough time to try https://github.com/DISTRHO/juce now.

So I will close this PR for now, but will definitely try LV2 for mac and windows again once the official JUCE supports LV2 :)
