### ISSUE TITLE
[REQ] Add the possibilty to save presets in a proprietary format

### ISSUE THREAD

**Issue by fedeb1979** [utokusa/OS-251#25]
As per title, if possible. Thanks!

**Comment by utokusa** [comment]
Thanks for these issues!

Originally I thought users were not interested in the feature because they can still save their own presets in .aupreset or .vstpreset .
But I got several requests and questions about it.
So, I will work on it in near future :)

**Comment by utokusa** [comment]
Hi @fedeb1979 
I have just merged the [PR](https://github.com/utokusa/OS-251/pull/29) for proprietary preset manager.
It will be something like this :)

<img width="804" alt="スクリーンショット 2021-10-03 16 17 56" src="https://user-images.githubusercontent.com/54586159/135744145-95b11ad6-8f4c-41b0-a482-c164555e015a.png">
<img width="757" alt="スクリーンショット 2021-10-03 16 18 07" src="https://user-images.githubusercontent.com/54586159/135744146-de79d9da-a04e-460a-b2fa-bb93da635275.png">

It's not released yet, but you can try the [new binary](https://github.com/utokusa/OS-251/actions/runs/1299922289#:~:text=environments/issues/4060-,Artifacts,-Produced%20during%20runtime) if you want.
(Note that the format might be changed before the release.)

Thanks!
